### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by psmoros** [harlan-zw/zhead#12]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@ohb00) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by harlan-zw** [comment]
Hey

My email is public on GitHub, feel free to reach out. Otherwise, feel free to post it publicly.

If it's XSS-related then I don't consider it a security issue.

**Comment by OhB00** [comment]
Thanks for your reply @harlan-zw. Wondering if you also consider the issue to not be a security issue within [unjs/unhead](https://github.com/unjs/unhead)?

**Comment by OhB00** [comment]
Just seen https://github.com/vueuse/head/issues/173, understand

**Comment by harlan-zw** [comment]
Hey @OhB00 

Thanks for reviewing the code :) 

Yup, that issue should give some context. 

Basically, it's a trade-off between DX and users doing bad things with data. As mentioned in the issue, a XSS safe version of the composable would be introduced for users to use who have untrusted data.

But it would be great to hear your thoughts on that solution or any ideas you have on solving it.

**Comment by harlan-zw** [comment]
Will move this to the unhead repo, utils have been removed from here as of 2.x
