### ISSUE TITLE
Support media query for `theme-color`

### ISSUE THREAD

**Issue by stone-zeng** [harlan-zw/zhead#14]
### Clear and concise description of the problem

In [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color), it says

> You can provide a media type or query inside the [media](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#media) attribute; the color will then only be set if the media condition is true.

But zhead currently only support `string` for `theme-color`:

https://github.com/harlan-zw/zhead/blob/a1449085ad3233582a3f9a31072ba6f2937a6530/src/metaFlat.ts#L631-L637

Please consider to extent the type definition to support media query. Thank you!

### Suggested solution

Possible interface:

```ts
export interface MetaFlat {
  themeColor: string | {
    name: string
    media: string
  }
}
```

**Comment by harlan-zw** [comment]
Hey @stone-zeng, great idea!

This is now available in the latest version of zhead and Unhead.
