### ISSUE TITLE
`profile` namespace

### ISSUE THREAD

**Issue by dargmuesli** [harlan-zw/zhead#16]
### Clear and concise description of the problem

I'd like add `profile:username` to one of my pages and am wondering if the profile subvalues listed here are supported: https://ogp.me/#type_profile

### Suggested solution

If not, would it be possible to add them?

### Additional context

NextSeo seems to support these types: https://github.com/garmeeh/next-seo#nextseo-options

**Comment by harlan-zw** [comment]
Great idea, would you be interested in sending a PR to support it?
