### ISSUE TITLE
Is canonical url available through useSeoMeta?

### ISSUE THREAD

**Issue by leopoldkristjansson** [harlan-zw/zhead#22]
### Details

Should I be able to set the canonical url in Nuxt 3 using `useSeoMeta()`?

The [Nuxt 3 docs](https://nuxt.com/docs/api/composables/use-seo-meta) point to this file when it comes to seeing the list of available options for `useSeoMeta()`: https://github.com/harlan-zw/zhead/blob/main/src/metaFlat.ts

The file does have a comment about canonical, but there is no property listed:

https://github.com/harlan-zw/zhead/blob/main/src/metaFlat.ts#L348

<img width="1291" alt="Screenshot 2023-12-21 at 12 02 39" src="https://github.com/harlan-zw/zhead/assets/2579324/8276bcb9-10f5-4396-9b26-af4333a39382">

**Comment by harlan-zw** [comment]
Hi @leopoldkristjansson 

The `useSeoMeta` is a DX layer for adding meta tags, the canonical tag is a `link` and is therefore not included in the composable.

If you want to set a canonical you can do so like this:

```ts
useHead({
  link: [{ rel: 'canonical', href: '<url>'  }],
})
```

**Comment by leopoldkristjansson** [comment]
> Hi @leopoldkristjansson
> 
> The `useSeoMeta` is a DX layer for adding meta tags, the canonical tag is a `link` and is therefore not included in the composable.
> 
> If you want to set a canonical you can do so like this:
> 
> ```ts
> useHead({
>   link: [{ rel: 'canonical', href: '<url>'  }],
> })
> ```

Makes sense. I am using `useHead` currently for the canonical. Just wondering about the code comment in `metaFlat.ts`, is it there for a reason?

**Comment by harlan-zw** [comment]
Yes, the `og:url` is used the same as the canonical url for the [open graph protocol](https://ogp.me/). I'm not sure why or if they would ever be different but they are distinct. 

The best practice is to provide both and have them the same

**Comment by leopoldkristjansson** [comment]
> Yes, the `og:url` is used the same as the canonical url for the [open graph protocol](https://ogp.me/). I'm not sure why or if they would ever be different but they are distinct and they both represent the canonical URL.
> 
> The best practice afaik is to provide both and have them the same.
> 
> ```ts
> const canonicalUrl = () => '<url>'
> useHead({
>   link: [{ rel: 'canonical', href: canonicalUrl }],
> })
> useSeoMeta({
>   ogUrl: canonicalUrl
> })
> ```

OK, I guess in almost all cases they would be the same, but I can still think of situations where they might be different. For example situations I've encountered on multilingual sites.

English is the "main" language. Here is an article written in English.

- https://www.example.com/news/my-article-about-something
- Canonical: https://www.example.com/news/my-article-about-something
- OG:URL: https://www.example.com/news/my-article-about-something

The site is available in German, but not all articles are translated, but are still made available to those browsing the German version of the site.

- https://www.example.com/de-de/nachrichten/my-article-about-something
- Canonical: https://www.example.com/news/my-article-about-something
- OG:URL: https://www.example.com/de-de/nachrichten/my-article-about-something

**Comment by harlan-zw** [comment]
I don't think this is a valid use case, i18n should be handled by its own set of tags. If the article isn't translated then it should redirect to the URL with the default locale instead.

Either way, it doesn't matter, this package isn't interested in how people use these tags, it's just providing a slightly nicer DX way of using them.

So it's not clear what the point of this issue is

**Comment by leopoldkristjansson** [comment]
> If the article isn't translated then it should redirect to the URL with the default locale instead.

Not sure I agree there for UX reasons, as that would move the user from the language they are browsing in (e.g. `/de-de` - German) to another language (`/` - English). Switching the whole UI over to English. That being said, this is debatable edge-case-land and not the reason for the initial question. 

```
Either way, it doesn't matter, this package isn't interested in how people use these tags, it's just providing a slightly nicer DX way of using them.

So it's not clear what the point of this issue is
```

Yes, absolutely. No issue at all. Just a question to clarify whether canonical could be set using `useSeoMeta`.
