### ISSUE TITLE
Missing potential Link#type for opensearch manifests

### ISSUE THREAD

**Issue by Tristan971** [harlan-zw/zhead#23]
### Describe the bug

Hi,

For websites to enable browsers to natively detect and offer their search feature to users, the [opensearch description](https://developer.mozilla.org/en-US/docs/Web/OpenSearch#autodiscovery_of_search_plugins) feature is the standard, and works by:
1. Serving an XML description file (name, icon, query template...)
2. Adding an HTML link node in the page's head, with type `application/opensearchdescription+xml`, pointing to it

This MIME type is not part of the allowed values for the `type` property. And it is mandatory to specify it for cross-browser compatibility.

NB: I'd strongly question wanting an exhaustive typing of MIME types in general though. When accounting for vendor extensions, format specifiers (+xml), charset specifiers (;charset=utf-8), etc., it is not possible to be exhaustive.

### Reproduction

https://stackblitz.com/edit/github-uy7ekg?file=nuxt.config.ts

### System / Nuxt Info

```Shell
Nuxt 3.12.1 + zhead 2.2.4
```

**Comment by markbrouch** [comment]
I'm running into the same issue on Nuxt with a link type `image/x-icon`, which is a valid MIME type for icon files. I would also question the desirability of an exhaustive typing of MIME types for this reason.

**Comment by markbrouch** [comment]
Following up with a discussion thread in the [Nuxt discord](https://discord.com/channels/473401852243869706/1042756264205230081/threads/1250177163198468147):

W3C specs state that the `type` attribute *must* be a valid MIME type string: https://html.spec.whatwg.org/multipage/semantics.html#attr-link-type

A valid MIME type string is then defined as: "a string that matches the media-type token production." https://mimesniff.spec.whatwg.org/#valid-mime-type

The media-type token production is simply a case-insensitive pair of strings separated by a `/` with an optional semicolon delimited parameters as key/value pairs separated by `=`. For example: `text/html;charset=utf-8`. https://www.rfc-editor.org/rfc/rfc9110#name-media-type

Therefore, I think think the appropriate type should be simply `string` until such time as a regex type is supported in TypeScript.

**Comment by harlan-zw** [comment]
Thank you for the detailed issue.

The link `type` is not meant to be exhaustive, the options provided are only there to improve IDE auto-completion. It's typed to ` (string & Record<never, never>)` at the end which is the equivalent of a `string` (that doesn't break auto-completions in some IDEs).

This was a Nuxt bug related to the types being serialized, see https://github.com/nuxt/nuxt/pull/27540/files.
